import { StyleSheet } from "react-native";
import { colors } from "../../../appTheme";

const styles = StyleSheet.create({
    background:{
        backgroundColor:colors.background,
        flex:1
    },
    header:{
        backgroundColor:colors.primary,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingVertical:15,
        paddingHorizontal:10
    },
    headerTitle:{
        flexDirection:'row'
    },
    title:{
        color:colors.white,
        fontWeight:'bold',
        fontSize:18,
        marginLeft:10
    },
    headerLeft:{
        color:colors.primary,
        fontWeight:'300',
        padding:10
    },
    info:{
        fontSize:14,
        fontWeight:'600',
        width:'90%',
        alignSelf:'center',
        marginVertical:20
    },
    infoType:{
        color:'#1A73E8',
        width:'90%',
        fontWeight:'600',
        alignSelf:'center',
        fontSize:12,
        marginVertical:10
    },
    typeHolder:{
        width:'90%',
        alignSelf:'center',
        flexDirection:'row',
    },
    type:{
        flexDirection:'row',
        alignItems:'center',
        width:'50%',
        marginVertical:15
    },
    typeText:{
        color:colors.darkText,
        marginLeft:10,
        width:'90%'
    },
    line:{
        height:20,
        borderBottomWidth:1,
        borderColor:colors.grey,
        width:'90%',
        alignSelf:'center',
        borderStyle:'dashed',
        marginBottom:30,        
        
    },
    uploadContainer:{
        borderWidth:1,
        borderColor:colors.grey,
        width:'90%',
        alignSelf:'center',
        borderStyle:'dashed',
        borderRadius:4,
        padding:20,
        flexDirection:'row',
        alignItems:'center'
    },
    uploadTxt:{
        color:'#1A73E8',
        width:'90%',
        marginLeft:10,
        fontWeight:'600',
        fontSize:16

    },
    uploadDescription:{
        width:'90%',
        alignSelf:'center',
        fontWeight:'400',
        fontSize:12,
        marginTop:10
    },
    btn:{
        backgroundColor:colors.lightGrey,
        width:'90%',
        alignSelf:'center',
        padding:15,
        justifyContent:'center',
        alignItems:'center',
        marginTop:30,
    },
    btnSelected:{
        backgroundColor:colors.primary,
        width:'90%',
        alignSelf:'center',
        padding:15,
        justifyContent:'center',
        alignItems:'center',
        marginTop:30,
    },
    btnTxt:{
        color:colors.grey,
        fontSize:16,
        fontWeight:'600'
    },
    btnTxtSelected:{
        color:colors.white,
        fontSize:16,
        fontWeight:'600'
    },
    selectedDoc:{
        width:'90%',
        alignSelf:'center',
        borderBottomWidth:1,
        borderColor:colors.grey,
        borderStyle:'dashed',
        padding:20,
        marginBottom:20,
    },
    selectedTitle:{
        fontSize:14,
        color:colors.darkText
    },
    selectedNameHolder:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:5
    },
    selectedNameTxt:{
        fontSize:18,
        fontWeight:'400'
    }

});

export default styles;