import { StyleSheet } from "react-native";
import { colors } from "../../../../appTheme";

const styles = StyleSheet.create({
    background:{
        backgroundColor:colors.background,
        flex:1
    },
    header:{
        backgroundColor:colors.primary,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        paddingVertical:15,
        paddingHorizontal:10
    },
    headerTitle:{
        flexDirection:'row'
    },
    title:{
        color:colors.white,
        fontWeight:'bold',
        fontSize:18,
        marginLeft:10
    },
    headerLeft:{
        color:colors.primary,
        fontWeight:'300',
        padding:10
    },
    chatBody:{
        flex:1
    },
    chatInput:{
        flexDirection:'row',
        width:'90%',
        alignSelf:'center',
        justifyContent:'space-between',
        alignItems:'center',
        marginBottom:20,
    },
    input:{
        flexDirection:'row',
        alignItems:'center',
        backgroundColor:colors.lightGrey,
        width:'85%',
        paddingHorizontal:10,
        borderRadius:50
    },
    inputEntry:{
        width:'90%',
        color:colors.lightText,
    },
    chatCard:{
        flexDirection:'row',
        width:'90%',
        alignSelf:'center',
        marginVertical:20,
    },
    chatText:{
        color:colors.darkText,
        width:'80%',
        paddingHorizontal:20,
        paddingVertical:10,
        backgroundColor:colors.grey,
        borderRadius:100,
        marginHorizontal:10,
        fontSize:14
    },
    chatTime:{
        color:colors.lightText,
        marginHorizontal:10,
        marginTop:5,
        fontSize:12
    },
    sentCard:{
        flexDirection:'row-reverse',
        justifyContent:'flex-start',
        width:'90%',
        alignSelf:'center',
        marginVertical:20,
    },
    sentText:{
        width:'80%',
        alignSelf:'flex-end',
        color:colors.white,
        paddingHorizontal:20,
        paddingVertical:10,
        backgroundColor:colors.primary,
        borderRadius:100,
        marginHorizontal:10,
        fontSize:14
    },
    sentTime:{
        color:colors.lightText,
        marginHorizontal:10,
        marginTop:5,
        fontSize:12,
        alignSelf:'flex-end',
        
    },
});
export default styles;