export const LOGOUT = 'LOGOUT';
export const UPDATE_PAYMENT_INFO = 'UPDATE_PAYMENT_INFO';
export const LOGIN = 'LOGIN';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_APPLIED_JOBS = 'UPDATE_APPLIED_JOBS';
